homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 
  longitude: 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  #  elevation: 199
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/


sensor:
    - platform: darksky
      api_key: DARK-SKY-API-KEY
      monitored_conditions:
        - summary
        - temperature
        - hourly_summary
        - temperature_max


script: !include_dir_named scripts

media_player:
  - platform: vlc
    name: computer_speaker

#media_player:
  #- platform: webostv
    #host: 192.168.0.10
    #mac: C8:08:E9:99:99:1A
    #name: Living Room TV
    #timeout: 5
    #filename: webostv.conf

ifttt:
  key: IFTTT-MAKER-KEY

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
